#ifndef _ANIMATION_ENUMS_H_
#define _ANIMATION_ENUMS_H_

#include "debugHeader.h"

enum AnimationType
{
	ONLY_ANIMATION_TYPE,
	RELATIVE_TRANSFORM,
	ABSOLUTE_TRANSFORM,
	OUTOFBOUNDS_ANIMATION_TYPE
};

#endif