#ifndef _EFFECT_TECHNIQUE_H_
#define _EFFECT_TECHNIQUE_H_

namespace EffectTechniques
{
	enum TechniqueType
	{
		NORMAL,
		AMBIENT,
		ADD_DIRECTIONAL,
		ADD_POINT,
		ADD_AREA,
		SHADOW_VOLUME,
		SHADOW_VOLUME_SHOW,
		SHADOW_VOLUME_DIRECTIONAL,
		SHADOW_VOLUME_POINT,
		QUAD,
		QUAD_DOWNSAMPLE,
		QUAD_TONEMAPPING,
		STREAK,
		FROM_LIGHT,
		PP_MOTION_BLUR,
		CUBE_MAP,
		DEPTH,
		RECONSTRUCT_WORLD,
		DEPTH_NORMAL_ALBEDO,
		DEFERRED_DIRECTIONAL,
		DEFERRED_POINT,
		DEFERRED_SPOT,
		DEFERRED_POINT_MESH,
		SSAO,
	};
};

#endif